paginate: 5
paginate_path: "/blog/page/:num"
name: Ketan Parmar
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
#gems: ['jekyll-lunr-js-search']
lunr_search:
  excludes: [atom.xml, sitemap.xml, index.html]

title: Software developer, trainer, speaker and more by Ketan Parmar
author: Ketan Parmar
description: Ketan Parmar is a software developer, trainer, speaker.
email: contact@kpbird.com
url: http://kpbird.com
rss_name: feed.xml
rss_post_limit: 10
permalink: /:year/:month/:title
